# Generated by Django 2.1.11 on 2020-03-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edit',
            old_name='title',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='edit',
            name='time',
        ),
        migrations.AddField(
            model_name='edit',
            name='coment',
            field=models.TextField(default=''),
        ),
    ]
