# Generated by Django 2.1.11 on 2020-03-16 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0003_edit_otherimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='edit',
            name='otherimg',
        ),
        migrations.AddField(
            model_name='feedfile',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='second.Edit'),
        ),
    ]
